# These are supported funding model platforms

custom: ['https://lp.ufx.com/es-es/t2/btc/v1/ff/?TLID=59134&utm_source=google&utm_medium=search&utm_term=b_%20monero&ADserver=407818236676&AdData=c&utm_content=es_btc&utm_campaign=monero&gclid=EAIaIQobChMI09DzgsiQ5wIVx5TVCh0qRw5hEAAYASAAEgLp-vD_BwE']
